Repository uber/orbit, pull requests merged in 2020-12, with the labels that each got.

#303 add unit tests to assert reproducibility of train and predict
  tests/orbit/models/test_lgt.py
Labels: enhancement

#280 Integrating LGT/DLT into ETS Base
  examples/DLT_Example2.ipynb
  examples/ETS.ipynb
  examples/LGT_Example.ipynb
  examples/archive/Regression_Advance1.ipynb
  orbit/constants/dlt.py
  orbit/constants/ets.py
  orbit/constants/lgt.py
  orbit/diagnostics/plot.py
  orbit/estimators/stan_estimator.py
  orbit/models/dlt.py
  orbit/models/ets.py
  orbit/models/lgt.py
  orbit/pyro/lgt.py
  orbit/stan/dlt.stan
  orbit/stan/ets.stan
  orbit/stan/lgt.stan
  tests/conftest.py
  tests/orbit/models/test_dlt.py
  tests/orbit/models/test_ets.py
  tests/orbit/models/test_lgt.py
  tests/resources/iclaims.example.csv
Labels: WIP, refactoring, review needed

#307 Documentation of release process in RELEASE.md
  RELEASE.md
Labels: documentation
