Repository uber/orbit, pull requests merged in 2021-02, with the labels that each got.

#349 Dev ktr cleanup
  examples/KTR_Example.ipynb
  examples/KTR_Pyro_Example.ipynb
  orbit/__init__.py
  orbit/constants/constants.py
  orbit/constants/ktr.py
  orbit/constants/ktrlite.py
  orbit/constants/ktrx.py
  orbit/models/ktr.py
  orbit/models/ktrlite.py
  orbit/models/ktrx.py
  orbit/pyro/ktr.py
  orbit/pyro/ktrlite.py
  orbit/pyro/ktrx.py
  orbit/stan/ktr.stan
  orbit/utils/kernels.py
  orbit/utils/timepoints.py
  tests/conftest.py
  tests/orbit/models/test_ktrlite.py
  tests/orbit/models/test_ktrx.py
  tests/utils/utils.py
Labels: review needed

#359 Provide Inference for MAP and Aggregated Estimator
  examples/ETS.ipynb
  examples/quick_start_LGT.ipynb
  orbit/exceptions.py
  orbit/models/base_model.py
  orbit/models/dlt.py
  orbit/models/ets.py
  orbit/models/lgt.py
  orbit/models/template.py
  orbit/utils/predictions.py
  tests/orbit/models/test_dlt.py
  tests/orbit/models/test_ets.py
  tests/orbit/models/test_lgt.py
Labels: new feature

#362 Dev tutorials update
  README.md
  docs/about.rst
  docs/conf.py
  docs/index.rst
  docs/tutorials.rst
  docs/tutorials/backtest.ipynb
  docs/tutorials/decompose_prediction.ipynb
  docs/tutorials/dlt.ipynb
  docs/tutorials/lgt.ipynb
  docs/tutorials/model_diagnostics.ipynb
  docs/tutorials/model_estimations.ipynb
  docs/tutorials/pyro_basic.ipynb
  docs/tutorials/quick_start.ipynb
  docs/tutorials/quick_start_DLT.ipynb
  docs/tutorials/quick_start_LGT.ipynb
  docs/tutorials/regression.ipynb
  examples/archive/Regression_Advance1.ipynb
  examples/backtest.ipynb
  examples/daily_forecast.ipynb
  examples/dlt.ipynb
  examples/docstring_inheritance_check.ipynb
  examples/ets_example.ipynb
  examples/hyper_parameters_tuning.ipynb
  examples/lgt.ipynb
  examples/lgt_pyro.ipynb
  examples/mcmc_diagnosttic.ipynb
  examples/regression1.ipynb
  examples/regression2.ipynb
  orbit/__init__.py
  orbit/initializer/dlt.py
  orbit/initializer/lgt.py
  requirements.txt
Labels: WIP, tutorial

#367 Some documentation change
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  RELEASE.md
  docs/img/orbit-banner640x320.png
  setup.py
Labels: WIP, documentation
