Repository uber/orbit, pull requests merged in 2021-03, with the labels that each got.

#372 add changelogs
  README.md
  RELEASE.md
  docs/changelog.rst
  docs/index.rst
Labels: review needed

#381 Remove sklearn
  orbit/diagnostics/backtest.py
  requirements.txt
  tests/conftest.py
  tests/orbit/models/test_lgt.py
  tests/utils/__init__.py
  tests/utils/utils.py
Labels: deprecation

#380 merge dev-ktr to dev
  docs/index.rst
  docs/tutorials/ktrlite.ipynb
  examples/ktrlite.ipynb
  orbit/constants/ktrlite.py
  orbit/diagnostics/plot.py
  orbit/models/ktrlite.py
  orbit/models/template.py
  orbit/stan/ktrlite.stan
  orbit/utils/features.py
  orbit/utils/kernels.py
  tests/conftest.py
  tests/orbit/models/test_ktrlite.py
Labels: new feature

#384 Refactoring of Templates, Fixing Labels with and w/o prefix "_", Fixing bugs in Initial Values of Sampling
  docs/tutorials/backtest.ipynb
  docs/tutorials/decompose_prediction.ipynb
  docs/tutorials/dlt.ipynb
  docs/tutorials/ktrlite.ipynb
  docs/tutorials/lgt.ipynb
  docs/tutorials/model_diagnostics.ipynb
  docs/tutorials/model_estimations.ipynb
  docs/tutorials/pyro_basic.ipynb
  docs/tutorials/quick_start.ipynb
  docs/tutorials/regression.ipynb
  orbit/__init__.py
  orbit/constants/dlt.py
  orbit/constants/ets.py
  orbit/constants/ktrlite.py
  orbit/constants/lgt.py
  orbit/initializer/dlt.py
  orbit/initializer/ets.py
  orbit/initializer/lgt.py
  orbit/models/dlt.py
  orbit/models/ets.py
  orbit/models/ktrlite.py
  orbit/models/lgt.py
  orbit/models/template.py
  orbit/stan/dlt.stan
  tests/conftest.py
  tests/orbit/models/test_dlt.py
  tests/orbit/models/test_ets.py
  tests/orbit/models/test_lgt.py
Labels: refactoring, review needed

#394 Refine Template - refine set dynamic attributes
  docs/tutorials/build_your_own_model.ipynb
  orbit/models/dlt.py
  orbit/models/ets.py
  orbit/models/ktrlite.py
  orbit/models/lgt.py
  orbit/models/template.py
Labels: refactoring, tutorial
