Repository uber/orbit, pull requests merged in 2021-07, with the labels that each got.

#461 Backtest Enhancement
  orbit/diagnostics/backtest.py
  orbit/diagnostics/metrics.py
  tests/conftest.py
  tests/orbit/diagnostics/test_backtest.py
Labels: new feature

#464 Update template.py
  orbit/models/template.py
Labels: refactoring, review needed

#434 expanding palette
  examples/color_palettes_testing.ipynb
  examples/eda_orbit_style.ipynb
  orbit/constants/palette.py
  orbit/eda/OrbitSignature.mplstyle
  orbit/eda/eda_plot.py
Labels: WIP

#473 Refine previous changes on palette
  examples/backtest.ipynb
  examples/color_palettes_testing.ipynb
  examples/eda_orbit_style.ipynb
  examples/ets_example.ipynb
  orbit/constants/palette.py
  orbit/diagnostics/backtest.py
  orbit/diagnostics/plot.py
  orbit/eda/eda_plot.py
  orbit/plot_style.mplstyle
  orbit/utils/plot.py
Labels: refactoring, review needed
