Repository uber/orbit, pull requests merged in 2022-04, with the labels that each got.

#708 Add black linting
  .github/workflows/black.yaml
  CONTRIBUTING.md
  docs/conf.py
  orbit/__init__.py
  orbit/constants/constants.py
  orbit/constants/palette.py
  orbit/diagnostics/backtest.py
  orbit/diagnostics/metrics.py
  orbit/diagnostics/plot.py
  orbit/eda/eda_plot.py
  orbit/estimators/base_estimator.py
  orbit/estimators/pyro_estimator.py
  orbit/estimators/stan_estimator.py
  orbit/forecaster/forecaster.py
  orbit/forecaster/full_bayes.py
  orbit/forecaster/map.py
  orbit/forecaster/svi.py
  orbit/models/dlt.py
  orbit/models/ets.py
  orbit/models/ktr.py
  orbit/models/ktrlite.py
  orbit/models/lgt.py
  orbit/pyro/ktr.py
  orbit/pyro/lgt.py
  orbit/template/dlt.py
  orbit/template/ets.py
  orbit/template/ktr.py
  orbit/template/ktrlite.py
  orbit/template/lgt.py
  orbit/template/model_template.py
  orbit/utils/dataset.py
  orbit/utils/features.py
  orbit/utils/general.py
  orbit/utils/kernels.py
  orbit/utils/knots.py
  orbit/utils/params_tuning.py
  orbit/utils/plot.py
  orbit/utils/predictions.py
  orbit/utils/pyro.py
  orbit/utils/simulation.py
  orbit/utils/stan.py
  pyproject.toml
  requirements-test.txt
  setup.py
  tests/conftest.py
  tests/orbit/diagnostics/test_backtest.py
  tests/orbit/diagnostics/test_eda_plot.py
  tests/orbit/diagnostics/test_plot.py
  tests/orbit/diagnostics/test_wbic.py
  tests/orbit/estimators/test_pyro_estimator.py
  tests/orbit/estimators/test_stan_estimator.py
  tests/orbit/models/test_dlt.py
  tests/orbit/models/test_ets.py
  tests/orbit/models/test_ktr.py
  tests/orbit/models/test_ktrlite.py
  tests/orbit/models/test_lgt.py
  tests/orbit/utils/test_knots.py
  tests/test_example.py
  tests/test_setup.py
Labels: WIP, backend

#740 Create dlt-animation.ipynb
  examples/dlt-animation.ipynb
Labels: documentation

#743 Refactor param tuning
  CONTRIBUTING.md
  examples/dlt_daily_forecast.ipynb
  examples/hyper_parameters_tuning.ipynb
  orbit/diagnostics/plot.py
  orbit/utils/knots.py
  orbit/utils/params_tuning.py
  orbit/utils/simulation.py
  tests/orbit/models/test_dlt.py
  tests/orbit/models/test_lgt.py
  tests/orbit/utils/params_tuning.py
Labels: enhancement
